[package]
name = "awesome-glib"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
darling = "0.12"

[lib]
proc-macro = true

[dev-dependencies]
glib = "0.14"
gio = "0.14"
