name: Build

"on":
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libgtk-4-dev xvfb
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --all-targets --verbose
    - name: Run tests
      run: xvfb-run cargo test --all-targets --verbose
      env:
        RUST_BACKTRACE: 1
