name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --all-targets --verbose
    - name: Run tests
      run: cargo test --all-targets --verbose
      env:
        RUST_BACKTRACE: 1
